version: '3.7'

services:
    php:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:80 -t public
        ports:
            - 80:80
        volumes:
            - .:/var/www

    composer:
        image: composer:2.2
        command: install
        volumes:
            - .:/app
